version: 0.2
env:
  parameter-store:
    ACCESS_KEY_ID: ACCESS_KEY_ID
    ACCOUNT_ID: ACCOUNT_ID
    SECRET_ACCESS_KEY: SECRET_ACCESS_KEY
    DEFAULT_REGION: DEFAULT_REGION
    #SECRET_NAME: SECRET_NAME

phases:
  pre_build:
    commands:
      - BRANCH=$(echo ${BRANCH} )
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 363780699952.dkr.ecr.ap-south-1.amazonaws.com
      - REPOSITORY_URI=$ACCOUNT_ID.dkr.ecr.$DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=build-$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')
      - export BRANCH
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:latest . --build-arg ACCESS_KEY_ID=$ACCESS_KEY_ID --build-arg SECRET_ACCESS_KEY=$SECRET_ACCESS_KEY --build-arg REGION=$DEFAULT_REGION --build-arg PORT=80 --build-arg SECRET_NAME=$SECRET_NAME
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo Writing image definitions file...
      - printf '[{"name":"%s","imageUri":"%s"}]' $CONTAINER_NAME $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
      - cat imagedefinitions.json
artifacts:
  files: imagedefinitions.json