input SignUp {
  type: AccountType!
  first_name: String! @constraint(pattern: "^[a-zA-Z\\s]*$", maxLength: 50)
  last_name: String!
  email: String! @constraint(format: "email", maxLength: 255)
  calling_code: String!
  mobile: String!
  password: String! @constraint(pattern: "^(?=.*\\d)(?=.*[a-z])(?=.*[A-Z]).{8,}", minLength: 8)
}

input InputSignIn {
  email: String! @constraint(format: "email", maxLength: 255)
  password: String!
}
