input SignUp {
  type: AccountType!
  first_name: String! @constraint(pattern: "^[a-zA-Z\\s]*$", maxLength: 50)
  last_name: String!
  email: String! @constraint(format: "email", maxLength: 255)
  password: String!
    @constraint(pattern: "^(?=.*\\d)(?=.*[a-z])(?=.*[A-Z]).{8,}", minLength: 8)
}

input InputSignIn {
  email: String! @constraint(format: "email", maxLength: 255)
  password: String!
}

input DateFilter {
  start: Date
  end: Date
}

input TaskFilter {
  id: Int
  title: String
  deadline: DateFilter
  startedat: DateFilter
  completedat: DateFilter
}

input NewTask {
  title: String! @constraint(pattern: "^[0-9a-zA-Z\\s]*$", minLength: 1, maxLength: 100)
  description: String
  deadline: String! @constraint(pattern: "^[0-9]{4}-[0-9]{2}-[0-9]{2}$", minLength: 10, maxLength: 10)
}

input UpdateTask {
  id: Int!
  title: String! @constraint(pattern: "^[0-9a-zA-Z\\s]*$", maxLength: 100)
  description: String
  deadline: Date!
  status: Status
}

input LogFilter {
  id: String
  first_name: String
  last_name: String
  originator_type: String
  originator: Int
  source: String
  url: String
  referer: String
  type: String
  method: String
  device: String
  browser: String
  brand: String
  ip: String
  starttime: Date 
  endtime: Date
  createdat: DateFilter
  status: String
  comment: String
  duration: JSON
}