type Query {
  signin(input: InputSignIn!): SignIn
  signout: Boolean
  tasks(filter: TaskFilter): [Task]
  task(id: Int!): Task
  logs(filter: LogFilter): [Log]
  verify(token: String!): Boolean
}

type Mutation {
  signup(input: SignUp!): SingUp
  add(input: NewTask!): Task
  update(input: UpdateTask!): Task
  delete(id: Int!): Task
}

type Subscription {
  show: Task!
}
