type SingUp {
  id: Int
  type: String
  firstname: String
  lastname: String
  email: String
  callingcode: String
  mobile: String
}

type SignIn {
  token: String
}

type Task {
  id: Int
  title: String
  description: String
  deadline: Date
  startedat: String
  completed: String
  userid: Int
  username: String
  status: String
  ago: JSON
}
