type SingUp {
  id: Int
  type: String
  firstname: String
  lastname: String
  email: String
  callingcode: String
  mobile: String
}

type SignIn {
  token: String
}

type Task {
  id: Int
  title: String
  description: String
  deadline: Date
  startedat: Date
  completed: Date
  userid: Int
  username: String
  status: String
  ago: JSON
}

type Log {
  id: String
  first_name: String
  last_name: String
  originator_type: String
  originator: Int
  source: String
  url: String
  referer: String
  type: String
  method: String
  device: String
  browser: String
  brand: String
  ip: String
  starttime: Date 
  endtime: Date
  createdat: Date
  status: String
  comment: String
  duration: JSON
}
