type SingUp {
  id: Int
  type: String
  firstname: String
  lastname: String
  email: String
  callingcode: String
  mobile: String
}

type SignIn {
  token: String
}

type Task {
  id: Int
  title: String
  description: String
  deadline: Date
  startedat: Date
  completed: Date
  userid: Int
  username: String
  status: String
  ago: JSON
  createdat: Date
}
